-- MySQL Script generated by MySQL Workbench
-- seg 10 fev 2020 13:56:15 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Curso` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Curso` (
  `idCurso` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idCurso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Turma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Turma` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Turma` (
  `idTurma` INT NOT NULL AUTO_INCREMENT,
  `curso_idCurso` INT NOT NULL,
  `sala` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL,
  PRIMARY KEY (`idTurma`),
  CONSTRAINT `fk_Turma_Curso1`
    FOREIGN KEY (`curso_idCurso`)
    REFERENCES `mydb`.`Curso` (`idCurso`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

SHOW WARNINGS;
CREATE INDEX `fk_Turma_Curso1_idx` ON `mydb`.`Turma` (`curso_idCurso` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) CHARACTER SET 'utf8mb4' NULL,
  `senha` VARCHAR(191) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL,
  `nome` VARCHAR(191) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL,
  `dtNasc` DATE NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Email_UNIQUE` ON `mydb`.`Usuario` (`email` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Aluno` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Aluno` (
  `idAluno` INT NOT NULL AUTO_INCREMENT,
  `usuario_idUser` INT NOT NULL,
  `turma_idTurma` INT NOT NULL,
  PRIMARY KEY (`idAluno`, `usuario_idUser`),
  CONSTRAINT `fk_Aluno_Turma`
    FOREIGN KEY (`turma_idTurma`)
    REFERENCES `mydb`.`Turma` (`idTurma`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Aluno_Usuario`
    FOREIGN KEY (`usuario_idUser`)
    REFERENCES `mydb`.`Usuario` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

SHOW WARNINGS;
CREATE INDEX `fk_Aluno_Turma_idx` ON `mydb`.`Aluno` (`turma_idTurma` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Aluno_Usuario_idx` ON `mydb`.`Aluno` (`usuario_idUser` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Professor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Professor` (
  `idProfessor` INT NOT NULL AUTO_INCREMENT,
  `usuario_idUser` INT NOT NULL,
  `formacao` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL,
  PRIMARY KEY (`idProfessor`, `usuario_idUser`),
  CONSTRAINT `fk_Professor_Usuario1`
    FOREIGN KEY (`usuario_idUser`)
    REFERENCES `mydb`.`Usuario` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

SHOW WARNINGS;
CREATE INDEX `fk_Professor_Usuario1_idx` ON `mydb`.`Professor` (`usuario_idUser` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Disciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Disciplina` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Disciplina` (
  `idDisciplina` INT NOT NULL AUTO_INCREMENT,
  `turma_idTurma` INT NOT NULL,
  `professor_idProfessor` INT NOT NULL,
  `assuntos` TEXT(60000) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL,
  `cargaHoraria` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL,
  PRIMARY KEY (`idDisciplina`),
  CONSTRAINT `fk_Disciplina_Turma1`
    FOREIGN KEY (`turma_idTurma`)
    REFERENCES `mydb`.`Turma` (`idTurma`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Disciplina_Professor1`
    FOREIGN KEY (`professor_idProfessor`)
    REFERENCES `mydb`.`Professor` (`idProfessor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

SHOW WARNINGS;
CREATE INDEX `fk_Disciplina_Turma1_idx` ON `mydb`.`Disciplina` (`turma_idTurma` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Disciplina_Professor1_idx` ON `mydb`.`Disciplina` (`professor_idProfessor` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Administrador` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Administrador` (
  `idAdministrador` INT NOT NULL AUTO_INCREMENT,
  `usuario_idUser` INT NOT NULL,
  PRIMARY KEY (`idAdministrador`, `usuario_idUser`),
  CONSTRAINT `fk_Administrador_Usuario1`
    FOREIGN KEY (`usuario_idUser`)
    REFERENCES `mydb`.`Usuario` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

SHOW WARNINGS;
CREATE INDEX `fk_Administrador_Usuario1_idx` ON `mydb`.`Administrador` (`usuario_idUser` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Aula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Aula` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Aula` (
  `idAula` INT NOT NULL AUTO_INCREMENT,
  `disciplina_idDisciplina` INT NOT NULL,
  `horarioInicio` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL,
  `horarioFim` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL,
  PRIMARY KEY (`idAula`),
  CONSTRAINT `fk_Aula_Disciplina1`
    FOREIGN KEY (`disciplina_idDisciplina`)
    REFERENCES `mydb`.`Disciplina` (`idDisciplina`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

SHOW WARNINGS;
CREATE INDEX `fk_Aula_Disciplina1_idx` ON `mydb`.`Aula` (`disciplina_idDisciplina` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
